"""add ai summary to paper

Revision ID: 813cad65adcd
Revises: 9308feb7d46e
Create Date: 2026-07-03 20:14:08.241994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813cad65adcd'
down_revision = '9308feb7d46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
